### ISSUE TITLE
finalize() not visible 

### ISSUE THREAD

**Issue by iagorios** [jeffdaily/parasail-java#1]
I'm getting "not visible method" error when calling result.finalize() from other classes.

**Comment by jeffdaily** [comment]
This is an example of my Java inexperience.  Object.finalize(), even though I have overridden it in the parasail classes Matrix, Result, and Profile, should not be called directly since it is protected.  The only thing finalize() does is call delete() -- and delete() has always been public.

I have updated parasail.Example and the README.md to tell users to call delete() to free any resources.  Sorry for the confusion.

See 2e70a4da516255e3edcd4c629432c027c79895da for the commit that correctly instructs users to call delete().
